#
# This file contains overrides for the RuboCop (https://github.com/bbatsov/rubocop) Ruby static code analyser.
#
Lint/UselessAssignment:
  Enabled: false

Metrics/AbcSize:
  Max: 40

Metrics/ClassLength:
  Max: 400

Metrics/LineLength:
  Max: 300

Metrics/MethodLength:
  Max: 30

Metrics/ParameterLists:
  Max: 6

Style/Documentation:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/EmptyLinesAroundBlockBody:
  Enabled: false

Style/EmptyLinesAroundClassBody:
  Enabled: false

Style/EmptyLinesAroundMethodBody:
  Enabled: false

Style/TrailingBlankLines:
  Enabled: false

Style/TrailingWhitespace:
  Enabled: false

Style/TrivialAccessors:
  Enabled: false
