language: ruby
rvm:
- 2.3.0

notifications:
  slack:
    secure: r5m5Lr7ZU/AKK00UFtpfrxvltt2Iye3zoZvIBVeUYvNa0dVRYeZidv+2VIi0zxMpVFN0Vx7rAL3njzbwZO/rrKuAJ7db8WbXKA1MMNpouF8LNvritMKeTqh4MX4SCcO172h+022qxACBJQDTAPXrdUwsuc1UwxLcdr6KVfCT+vx1S/leHC1hQ2t/Cvt3ScLr+bRu9sGWAH83zSPrKd4hsqosUGMpHg3RkM2GRIGgvoX6VfayDGeEysZyYefah7bHkQV8/BEUPDJPgCl5WFmiKSyMLEk1AfGmQwM4Nhr9Z9qG3r2sUgLQZLiOjq2ihvbfsukaeW2z9usWYk6yY/yRx62tGFiwLBA/1dean+VGtlS/ZnLBOKYJbqCzY/Zfcgsd5SV9T/qZ+8UT239xyV++kRw5iQrKQPC3ADWIhtTvg6aqVEmMTbAuDV2MI1DyWtkMfKM8lJ0H3j0syEKvAsMGb+pCmSYRcNz7uVFTO3gU8xcbp2eViEApWkf0jDp92ugmSF/5B+nIE4wVnQbBXjOocqvh0jia4T1qVtMc2W2JoYtOxP7SKs63qhAP5YdZbLkpeqRlmsplHwCYfXiRslJBQHDPbnfj7X1e78E6PF2EFfdvlChd30u+6ImKjDouFHEuFI+6qAy1dWBEPZJlDlCXUjXWPrFg5kzQ/V/9itM2D6k=
