language: python
sudo: required
dist: trusty
python: '3.6'

# before_install:

cache:
  - pip

install:
  - pip install pipenv
  - pipenv install --dev --deploy

script:
  - pipenv run inv flake8
  - pipenv run inv coverage
  - pipenv run coverage report

after_success:
  - pipenv run codecov

branches:
  only:
    - master
