env: minikube
namespace: minikube

replicas: 1
rollingUpdate:
  maxSurge: 1
  maxUnavailable: 1

image:
  devRepo: eu.gcr.io/ons-rasrmbs-management
  name: eu.gcr.io/ons-rasrmbs-management
  tag: latest
  pullPolicy: Always

database:
  managedRedis: false

container:
  port: 8080
service:
  port: 8080

resources:
  requests:
    memory: "128Mi"

dns:
  enabled: false
  wellKnownPort: 8080